Dodanie możliwości ustwienia ogłoszeń o kupnie na chacie
ivall/VIshop-plugin pull request #2
Opened 2022-08-19 14:36 UTC by maxcom1

* Dodano możliwość ustawienia ogłoszeń o kupnie na chacie (w configu)
* Zaktualizowano zależności
* Dodano instrukcję dotyczącą ogłoszeń do `README.md`

2022-08-19 19:10 UTC, Kamilkime requested changes

2022-08-19 19:10 UTC, Kamilkime commented on README.md
> +Plugin łączący serwer Minecraft z itemshopem stworzonym na [VIshop.pl](https://vishop.pl/)
A czemu usunąłeś to wymuszenie złamania wiersza?

2022-08-19 19:10 UTC, Kamilkime commented on README.md
> +# Wyświetlanie informacji o zakupie na chacie
To raczej nie powinno być h1, może h2 lub h3

2022-08-19 19:10 UTC, Kamilkime commented on README.md
> +**Konfiguracja na serwerze Minecraft**
Pytanie czy taki podtytuł potrzebny. Jeśli tak - lepiej użyć składni hx

2022-08-19 19:10 UTC, Kamilkime commented on README.md
> +w pliku konfiguracyjnym (`config.yml`).
Nawiasy przy nazwie pliku w sumie zbędne

2022-08-19 19:10 UTC, Kamilkime commented on README.md
> +...
Te kropki lepiej usunąć, bo ludzie przekleją z nimi

2022-08-19 19:10 UTC, Kamilkime commented on README.md
> +Istnieje możliwość dodania większej ilości ogłoszeń - inne dla każdego produktu.
Większej liczby i innego, a nie inne

2022-08-19 19:10 UTC, Kamilkime commented on README.md
> +Treść ogłoszeń dodajemy w yaml'owej liście - każda linijka tekstu na chacie w osobnym stringu.
Yaml czy string - nic wielu ludziom nie powie, nie ma co mieszać - lepiej na przykładach pokazać kilka

2022-08-19 19:10 UTC, Kamilkime commented on README.md
> +Ogłoszenia wspierają zarówno domyślne kolory chatu (np. `&6`), ale także własne kolory RGB (np. `&#123456`) - tylko spigot i jego forki (paper, purpur itd.).
Ale to wszystkie kolory tylko spigot wspiera? Czy tylko hex? Trochę niejasno napisane

2022-08-19 19:10 UTC, Kamilkime commented on README.md
> +**Konfiguracja w panelu VIshop**
Lepiej użyć hx

2022-08-19 19:10 UTC, Kamilkime commented on build.gradle
> +    compileOnly 'net.md-5:bungeecord-api:1.19-R0.1-SNAPSHOT' // for hex messages, only on spigot
Dodawanie całego API bungee tylko dla hex wiadomości to raczej nie jest dobry pomysł, szczególnie że chcemy wspierać wersje wygodnie od 1.8 (które mogło mieć starsze API) i nie chcemy się ograniczać tylko do spigotów

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/PendingTask.java
> +import java.util.Set;
Lepiej nie przestawiać tak nagle kolejności importów, tylko dostosować się do obecnej

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/PendingTask.java
> +                    List<String> messages = config.broadcastMessages.get(command.replaceAll("#", ""));
Lepiej substring, replaceAll będzie kosztowniejszy obliczeniowo

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/PendingTask.java
> +                    if (messages == null) return;
Klamry do ifa

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/PendingTask.java
> +                    messages.forEach(msg -> Bukkit.broadcastMessage(translateMessage(msg, order)));
Możemy to zrobić ładniej funkcyjnie - najpierw map() na wiadomościach, a dopiero potem forEach()

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/PendingTask.java
> +        return message.replaceAll("\\{NICK}", order.getPlayer());
Po pierwsze - lepiej używać StringUtils#replace
Ale po drugie i ważniejsze - zobacz na samo Order#getCommands, chyba ten replace w ogóle nie będzie potrzebny

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/config/Config.java
> +        this.broadcastMessages = new HashMap<>();
Takie coś na pewno wypadałoby wydzielić do innej metody - samo pobieranie tych broadcastów zajmuje więcej niż wszystko inne dotychczas

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/config/Config.java
> +        boolean translateHex = isSpigot && (Bukkit.getServer().getVersion().contains("1.16") || Bukkit.getServer().getVersion().contains("1.17") || Bukkit.getServer().getVersion().contains("1.18") ||
To na pewno nie może tak zostać - nie będziemy dodawać kolejnego warunku co wersja

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/config/Config.java
> +                messages.set(i, msg);
Nie wiem czemu set a nie add - można by to całe zrobić kompletnie funkcyjnie mapowaniami odpowiednimi

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/config/Config.java
> +                if (translateHex) msg = translateHex(msg);
Klamry

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/config/Config.java
> +            message = message.replace(hex, net.md_5.bungee.api.ChatColor.of(hex
Tak nie chcemy robić, bo zepsujemy kompatybilność z Bukkitem - jeśli koniecznie chcesz użyć tego API, to trzeba z tego zrobić inną klasę, która może nie być w ogóle wołana

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/config/Config.java
> +    private String translateHex(String message) {
Strasznie przekombinowany sposób - nie lepiej znaleźć jakąś libkę, która umie to zrobić bez zabaw w regexy, dzielenie stringa, itd? Po co właściwie to jest tak dzielone i kolorowane tylko kawałeczkami gdzie są kolory?

2022-08-19 19:10 UTC, Kamilkime commented on src/main/java/pl/vishop/vishopplugin/config/Config.java
> +    private static final Pattern hexPattern = Pattern.compile("&#[A-Fa-f0-9]{6}");;
Średnik za dużo, takie static pole powinno być na samej górze i nazywać się jak stała

2022-08-19 19:10 UTC, Kamilkime commented on src/main/resources/config.yml
> +# Więcej informacji na stronie pluginu (github)
Jeśli odsyłamy ludzi na GitHuba - trzeba im dać dokładny link, najlepiej z odniesieniem nawet do konkretnej sekcji README

2022-08-19 19:10 UTC, Kamilkime commented on src/main/resources/config.yml
> +    - ''
Domyślnie dałbym minimum dwa ogłoszenia, żeby ludzie widzieli o co chodzi. No i można dodać kolorek z hexem - najwyżej go komuś nie pokoloruje, ale przykład będzie

2022-08-19 19:12 UTC, maxcom1 commented on README.md
> +Plugin łączący serwer Minecraft z itemshopem stworzonym na [VIshop.pl](https://vishop.pl/)
> A czemu usunąłeś to wymuszenie złamania wiersza?
@Kamilkime w składni markdown z tego co wiem robi się dwoma spacjami

2022-08-19 19:15 UTC, Kamilkime commented on README.md
> +Plugin łączący serwer Minecraft z itemshopem stworzonym na [VIshop.pl](https://vishop.pl/)
Ah... No, człowiek uczy się całe zycie

2022-08-19 19:20 UTC, maxcom1 commented
nie to się kliknęło :v

2022-08-28 21:31 UTC, makindotcc commented on src/main/java/pl/vishop/vishopplugin/PendingTask.java
> +    public PendingTask(final ViShopPlugin plugin, final OkHttpClient httpClient, final Config config) {
Jeżeli potrzebujesz użyć "getBroadcastSender" to po wstrzyknij to konstruktorem tak jak reszta przekazanych tu rzeczy.

2022-11-25 19:05 UTC, Kamilkime commented
https://github.com/ivall/VIshop-plugin/issues/10#issuecomment-1327796107

2022-11-25 19:05 UTC, closed without merging